import { Artist, Artwork, Order, Message } from './types'

export const SEED_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    user_id: 'user-1',
    name: 'Sarah Chen',
    bio: 'Contemporary painter exploring light and shadow through acrylic and mixed media.',
    artist_statement: 'I create work that examines the intersection of abstraction and representation. My pieces are inspired by natural landscapes transformed through color and movement.',
    profile_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    location: 'Raleigh, NC',
    mediums: ['Acrylic', 'Mixed Media', 'Oil Paint'],
    price_range_min: 300,
    price_range_max: 5000,
    social_links: {
      instagram: 'https://instagram.com/sarahchenart',
      website: 'https://sarahchenart.com'
    },
    website: 'https://sarahchenart.com',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artist-2',
    user_id: 'user-2',
    name: 'Marcus Rodriguez',
    bio: 'Photographer capturing intimate moments in everyday life and urban environments.',
    artist_statement: 'My work is about finding beauty in the mundane. I photograph the moments people often overlook.',
    profile_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    location: 'Charlotte, NC',
    mediums: ['Photography', 'Digital Print'],
    price_range_min: 150,
    price_range_max: 2500,
    social_links: {
      instagram: 'https://instagram.com/mrodriguezphoto'
    },
    website: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artist-3',
    user_id: 'user-3',
    name: 'Elena Vasquez',
    bio: 'Sculptor working with clay, bronze, and found materials to create abstract forms.',
    artist_statement: 'Sculpture is my language. I work with materials to explore form, space, and the relationship between object and viewer.',
    profile_photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    location: 'Durham, NC',
    mediums: ['Clay', 'Bronze', 'Found Materials'],
    price_range_min: 800,
    price_range_max: 15000,
    social_links: {
      instagram: 'https://instagram.com/elenavasquezsculpture'
    },
    website: 'https://elenavasquez.art',
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artist-4',
    user_id: 'user-4',
    name: 'James Thompson',
    bio: 'Print artist specializing in linocut and woodblock printing with botanical themes.',
    artist_statement: 'I am drawn to the precision and imperfection of hand-printed work. Nature is my constant inspiration.',
    profile_photo_url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    location: 'Greensboro, NC',
    mediums: ['Linocut', 'Woodblock Print', 'Etching'],
    price_range_min: 75,
    price_range_max: 800,
    social_links: {
      instagram: 'https://instagram.com/jthompsonprints'
    },
    website: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
]

export const SEED_ARTWORKS: Artwork[] = [
  {
    id: 'artwork-1',
    artist_id: 'artist-1',
    title: 'Morning Light',
    slug: 'morning-light',
    description: 'A large-scale acrylic painting exploring the interplay of warm and cool tones.',
    category: 'painting',
    medium: 'Acrylic on Canvas',
    price: 1200,
    image_urls: ['https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800'],
    dimensions: '48" x 36"',
    orientation: 'landscape',
    color_tags: ['warm orange', 'soft yellow', 'cool blue', 'white'],
    year_created: 2023,
    edition_type: 'original',
    edition_size: null,
    edition_number: null,
    quantity_available: 1,
    condition: 'Excellent',
    is_framed: false,
    has_coa: true,
    shipping_price: 150,
    allows_offers: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-2',
    artist_id: 'artist-1',
    title: 'Abstract Serenity',
    slug: 'abstract-serenity',
    description: 'Mixed media work combining acrylic, ink, and collage elements.',
    category: 'painting',
    medium: 'Acrylic, Ink, Collage on Canvas',
    price: 850,
    image_urls: ['https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=800'],
    dimensions: '36" x 24"',
    orientation: 'landscape',
    color_tags: ['deep purple', 'gold', 'navy', 'white'],
    year_created: 2024,
    edition_type: 'original',
    edition_size: null,
    edition_number: null,
    quantity_available: 1,
    condition: 'Excellent',
    is_framed: true,
    has_coa: true,
    shipping_price: 120,
    allows_offers: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-3',
    artist_id: 'artist-2',
    title: 'Urban Geometry',
    slug: 'urban-geometry',
    description: 'A striking photograph capturing architectural lines and patterns in the city.',
    category: 'photography',
    medium: 'Archival Pigment Print',
    price: 450,
    image_urls: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800'],
    dimensions: '24" x 36"',
    orientation: 'portrait',
    color_tags: ['black', 'white', 'grey'],
    year_created: 2023,
    edition_type: 'limited',
    edition_size: 25,
    edition_number: 5,
    quantity_available: 2,
    condition: 'Excellent',
    is_framed: false,
    has_coa: true,
    shipping_price: 85,
    allows_offers: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-4',
    artist_id: 'artist-2',
    title: 'Rainfall',
    slug: 'rainfall',
    description: 'Intimate study of water droplets and reflections. A contemplative moment.',
    category: 'photography',
    medium: 'Archival Pigment Print',
    price: 350,
    image_urls: ['https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800'],
    dimensions: '16" x 20"',
    orientation: 'portrait',
    color_tags: ['cool blue', 'grey', 'white'],
    year_created: 2024,
    edition_type: 'limited',
    edition_size: 50,
    edition_number: 12,
    quantity_available: 3,
    condition: 'Excellent',
    is_framed: false,
    has_coa: true,
    shipping_price: 65,
    allows_offers: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-5',
    artist_id: 'artist-3',
    title: 'Form in Motion',
    slug: 'form-in-motion',
    description: 'Bronze sculpture exploring the tension between stillness and movement.',
    category: 'sculpture',
    medium: 'Cast Bronze',
    price: 3500,
    image_urls: ['https://images.unsplash.com/photo-1517242810446-cc8951b2be40?w=800'],
    dimensions: '18" H',
    orientation: 'portrait',
    color_tags: ['bronze', 'warm brown'],
    year_created: 2022,
    edition_type: 'limited',
    edition_size: 8,
    edition_number: 3,
    quantity_available: 1,
    condition: 'Excellent',
    is_framed: false,
    has_coa: true,
    shipping_price: 250,
    allows_offers: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-6',
    artist_id: 'artist-3',
    title: 'Emergence',
    slug: 'emergence',
    description: 'Clay sculpture with natural glazed finish. Exploring organic forms.',
    category: 'sculpture',
    medium: 'Glazed Ceramic',
    price: 1200,
    image_urls: ['https://images.unsplash.com/photo-1576020799627-aeac74d58064?w=800'],
    dimensions: '12" H x 8" W',
    orientation: 'portrait',
    color_tags: ['cream', 'soft grey', 'earth tone'],
    year_created: 2023,
    edition_type: 'original',
    edition_size: null,
    edition_number: null,
    quantity_available: 1,
    condition: 'Excellent',
    is_framed: false,
    has_coa: true,
    shipping_price: 120,
    allows_offers: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-7',
    artist_id: 'artist-4',
    title: 'Botanical Study #3',
    slug: 'botanical-study-3',
    description: 'Hand-printed linocut capturing the delicate structures of flowering plants.',
    category: 'print',
    medium: 'Linocut Print',
    price: 250,
    image_urls: ['https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=800'],
    dimensions: '12" x 16"',
    orientation: 'portrait',
    color_tags: ['deep green', 'black', 'cream'],
    year_created: 2024,
    edition_type: 'limited',
    edition_size: 100,
    edition_number: 34,
    quantity_available: 2,
    condition: 'Excellent',
    is_framed: false,
    has_coa: false,
    shipping_price: 35,
    allows_offers: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'artwork-8',
    artist_id: 'artist-4',
    title: 'Wildflower Series - Summer',
    slug: 'wildflower-summer',
    description: 'Part of an ongoing series exploring seasonal florals through woodblock printing.',
    category: 'print',
    medium: 'Woodblock Print',
    price: 180,
    image_urls: ['https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=800'],
    dimensions: '11" x 14"',
    orientation: 'landscape',
    color_tags: ['warm yellow', 'soft pink', 'sage green'],
    year_created: 2023,
    edition_type: 'limited',
    edition_size: 75,
    edition_number: 22,
    quantity_available: 3,
    condition: 'Excellent',
    is_framed: false,
    has_coa: false,
    shipping_price: 30,
    allows_offers: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
]

// Mock order and message data — used by the artist dashboard and buyer
// account pages until real data is wired up via Supabase.
export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    buyer_id: 'demo-buyer',
    artwork_id: 'artwork-3',
    artist_id: 'artist-2',
    amount: 450,
    buyer_fee: 59,
    shipping_cost: 85,
    status: 'shipped',
    tracking_number: '1Z999AA10123456784',
    created_at: '2026-04-12T10:00:00Z',
    updated_at: '2026-04-18T14:30:00Z'
  },
  {
    id: 'order-2',
    buyer_id: 'demo-buyer',
    artwork_id: 'artwork-7',
    artist_id: 'artist-4',
    amount: 250,
    buyer_fee: 33,
    shipping_cost: 35,
    status: 'delivered',
    tracking_number: '1Z999AA10123456785',
    created_at: '2026-03-02T15:20:00Z',
    updated_at: '2026-03-10T11:00:00Z'
  },
  {
    id: 'order-3',
    buyer_id: 'demo-buyer',
    artwork_id: 'artwork-8',
    artist_id: 'artist-4',
    amount: 180,
    buyer_fee: 23,
    shipping_cost: 30,
    status: 'accepted',
    created_at: '2026-05-10T09:15:00Z',
    updated_at: '2026-05-11T16:45:00Z'
  }
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    sender_id: 'demo-buyer',
    recipient_id: 'artist-1',
    artwork_id: 'artwork-1',
    content: "Hi Sarah, I love Morning Light. Is the framing custom or can I have it shipped unframed?",
    read: true,
    created_at: '2026-05-08T14:22:00Z'
  },
  {
    id: 'msg-2',
    sender_id: 'artist-1',
    recipient_id: 'demo-buyer',
    artwork_id: 'artwork-1',
    content: "Hi! The piece comes unframed — I find collectors prefer to choose framing that matches their space. Happy to recommend a framer in your area if helpful.",
    read: true,
    created_at: '2026-05-08T18:45:00Z'
  },
  {
    id: 'msg-3',
    sender_id: 'demo-buyer',
    recipient_id: 'artist-4',
    artwork_id: 'artwork-7',
    content: "Hi James, will there be more pieces in the Botanical Study series?",
    read: false,
    created_at: '2026-05-12T20:10:00Z'
  }
]

export const DEMO_BUYER_ID = 'demo-buyer'

export const CATEGORIES = ['painting', 'print', 'photography', 'sculpture']
export const COLORS = [
  'warm orange',
  'soft yellow',
  'cool blue',
  'white',
  'deep purple',
  'gold',
  'navy',
  'black',
  'grey',
  'bronze',
  'warm brown',
  'cream',
  'soft grey',
  'earth tone',
  'deep green',
  'warm yellow',
  'soft pink',
  'sage green'
]
